/** Agrochemical / formulation Wikipedia titles for bulk indexing */
export const WIKIPEDIA_CORPUS_TITLES = [
  'Pesticide',
  'Pesticide formulation',
  'Herbicide',
  'Insecticide',
  'Fungicide',
  'Surfactant',
  'Emulsion',
  'Suspension (chemistry)',
  'Wetting agent',
  'Dispersant',
  'HLB value',
  'Chlorpyrifos',
  'Glyphosate',
  'Imidacloprid',
  'Lambda-cyhalothrin',
  'Mancozeb',
  'Abamectin',
  'Atrazine',
  'Tebuconazole',
  'Azoxystrobin',
  'Paraquat',
  '2,4-Dichlorophenoxyacetic acid',
  'Neonicotinoid',
  'Pyrethroid',
  'Organophosphate',
  'Triazine',
  'Strobilurin',
  'Wettable powder',
  'Emulsifiable concentrate',
  'Suspension concentrate',
  'Water dispersible granule',
  'Capsule suspension',
  'Colloid',
  'Rheology',
  'Zeta potential',
  'Ostwald ripening',
  'Brownian motion',
  'Agrochemical',
  'Integrated pest management',
  'Biopesticide',
  'Adjuvant (chemical)',
  'Antifoam',
  'Xanthan gum',
  'Attapulgite',
  'Crop protection',
  'Good agricultural practice',
  'Maximum residue limit',
  'Globally Harmonized System of Classification and Labelling of Chemicals',
];
