import type { KnowledgeArticle } from '../types';

export const KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'sc-sedimentation',
    title: 'SC Sedimentation and Rheology Control',
    category: 'sedimentation',
    source_type: 'handbook',
    summary: 'Sedimentation in SCs arises from density differences, weak gel structure, or oversized particles.',
    content: 'Root causes: (1) D90 too large — incomplete milling; (2) insufficient thickener or wrong rheology model; (3) flocculation from electrolytes or temperature. Remedies: increase xanthan or attapulgite, optimize dispersant level, remill if D90 >5 µm. Preventive: cup test at 54°C, measure viscosity at low shear (Brookfield). References: Hunter, Foundations of Colloid Science; FAO formulation manual.',
    tags: ['sc', 'sedimentation', 'rheology'],
  },
  {
    id: 'ec-phase-sep',
    title: 'EC Phase Separation and Emulsion Stability',
    category: 'phase_separation',
    source_type: 'academic',
    summary: 'EC stability depends on HLB, solvent selection, and emulsifier ratio.',
    content: 'When EC creams or oils out: check HLB of emulsifier blend (target 10-12 for O/W dilution), reduce aromatic solvent if crystallization at low temp, add co-solvent. Jar test at 0.1% in 342 ppm water and 54°C storage. References: Rosen, Surfactants and Interfacial Phenomena.',
    tags: ['ec', 'emulsion', 'phase_separation'],
  },
  {
    id: 'crystal-growth',
    title: 'Crystal Growth in Aqueous Suspensions',
    category: 'crystal_growth',
    source_type: 'research',
    summary: 'Ostwald ripening and temperature cycling drive crystal growth in SC/EW.',
    content: 'Small particles dissolve and redeposit on larger crystals especially when log P is borderline. Mitigation: tighter particle size distribution, polymeric dispersants, storage temperature control, antifreeze in EW. For lambda-cyhalothrin SC use optimized dispersant + milling endpoint.',
    tags: ['crystal', 'sc', 'ew'],
  },
  {
    id: 'foam-control',
    title: 'Foam Control in Agrochemical Formulations',
    category: 'foam',
    source_type: 'industry',
    summary: 'Foam arises from surfactants and high-shear mixing; control with antifoam and process order.',
    content: 'Add silicone antifoam 0.05-0.2% late in process. Avoid over-mixing after antifoam. Defoamer incompatibility can cause haze — screen alternatives. Tank-side antifoams differ from in-can; do not double without testing.',
    tags: ['foam', 'antifoam', 'sc'],
  },
  {
    id: 'ph-drift',
    title: 'pH Drift and Hydrolysis',
    category: 'pH_drift',
    source_type: 'handbook',
    summary: 'Many AIs hydrolyze in alkaline water; buffer to product-specific pH.',
    content: 'Organophosphates and some triazines sensitive above pH 7. Use citric or phosphoric acid buffers. Check pH at 0.1% dilution after 24h storage. SL products often need pH 4-6.',
    tags: ['ph', 'hydrolysis', 'sl'],
  },
  {
    id: 'formulation-selection',
    title: 'Selecting Formulation Type from AI Properties',
    category: 'general',
    source_type: 'academic',
    summary: 'Rule-of-thumb matrix linking solubility, log P, and physical form to SC/EC/WDG/SL.',
    content: 'Water solubility >10 g/L → consider SL. Log P >3 and liquid AI → EC or EW. Solid, low solubility → SC or WDG. High volatility → CS. WP for cost-sensitive inorganics. Always confirm with 14-day accelerated stability.',
    tags: ['selection', 'formulation', 'rules'],
  },
  {
    id: 'hlb-system',
    title: 'HLB System for Emulsifier Selection',
    category: 'general',
    source_type: 'academic',
    summary: 'Griffin HLB scale guides emulsifier selection for O/W vs W/O.',
    content: 'Required HLB for oil phase estimated from oils table. Blend emulsifiers to match — e.g. Span 80 + Tween 20. For EC, calcium sulfonate + ethoxylate nonionic is classic. Verify with dilution emulsion clarity and particle size.',
    tags: ['hlb', 'emulsifier', 'ec', 'ew'],
  },
  {
    id: 'milling-sc',
    title: 'Wet Milling for Suspension Concentrates',
    category: 'general',
    source_type: 'industry',
    summary: 'Media milling reduces particle size; target D90 <5 µm for most SC.',
    content: 'Premix with dispersant before mill. Monitor energy input and temperature. Screen mill media wear. Oversized particles cause nozzle blockage and poor bioavailability.',
    tags: ['milling', 'sc', 'manufacturing'],
  },
  {
    id: 'regulatory-ghs',
    title: 'GHS Classification for Formulated Products',
    category: 'general',
    source_type: 'regulatory',
    summary: 'Hazard class derives from AI, co-formulants, and acute toxicity studies.',
    content: 'GHS pictograms for formulated product may differ from technical AI. Document in SDS. Common classes: Acute Tox, Skin Sens, Aquatic Acute/Chronic. Use official CLP/GHS tables.',
    tags: ['ghs', 'hazard', 'regulatory'],
  },
  {
    id: 'wdg-caking',
    title: 'WDG Caking and Moisture Uptake',
    category: 'other',
    source_type: 'handbook',
    summary: 'Humidity during storage causes caking in WDG/WP.',
    content: 'Improve packaging barrier, adjust binder level, add anti-caking silica. Disintegration test if product fails to break in water.',
    tags: ['wdg', 'storage', 'caking'],
  },
];

export const KNOWLEDGE_VOCABULARY = {
  hazard_classes: [
    'Acute Tox. 1', 'Acute Tox. 2', 'Acute Tox. 3', 'Acute Tox. 4',
    'Skin Irrit. 2', 'Eye Irrit. 2', 'Skin Sens. 1',
    'Aquatic Acute 1', 'Aquatic Chronic 1', 'Aquatic Chronic 2',
    'Repr. 2', 'Carc. 2', 'STOT SE 3',
  ],
  pest_categories: ['insecticide', 'herbicide', 'fungicide', 'acaricide', 'other'],
  physical_forms: ['solid', 'liquid', 'waxy'],
  formulation_codes: ['SC', 'EC', 'WDG', 'WP', 'EW', 'SL', 'CS', 'SE', 'OD', 'ZC', 'ME', 'DC'],
  suppliers: ['BASF', 'Croda', 'Evonik', 'Clariant', 'Solvay', 'Nouryon', 'Stepan', 'Innospec'],
};
