import type { KnowledgeFormulationType } from '../types';

export const KNOWLEDGE_FORMULATION_TYPES: KnowledgeFormulationType[] = [
  {
    code: 'SC',
    name: 'Suspension Concentrate',
    description: 'Stable suspension of solid AI in aqueous continuous phase with dispersants and thickeners.',
    best_for: ['Low to moderate water solubility solids', 'Medium particle size after wet milling'],
    advantages: ['Water-based', 'No dust', 'Good bioavailability when stable'],
    limitations: ['Sedimentation risk', 'Requires milling', 'Electrolyte sensitivity'],
    typical_ais: ['Chlorpyrifos', 'Imidacloprid', 'Lambda-cyhalothrin'],
    processing_notes: ['Media mill to D90 <5 µm', 'Add thickener last', 'Avoid foam during mixing'],
    tags: ['aqueous', 'solid-ai'],
  },
  {
    code: 'EC',
    name: 'Emulsifiable Concentrate',
    description: 'AI dissolved in solvent with emulsifier package; forms emulsion on dilution in water.',
    best_for: ['Hydrophobic liquids or solids', 'High log P actives'],
    advantages: ['Excellent leaf penetration', 'Established technology'],
    limitations: ['Solvent handling', 'Emulsion stability at low temp', 'Phytotoxicity risk with aromatics'],
    typical_ais: ['Lambda-cyhalothrin', 'Chlorpyrifos', 'Propiconazole'],
    processing_notes: ['HLB balance emulsifier pair', 'Jar test at 0.1% in standard water'],
    tags: ['solvent', 'emulsion'],
  },
  {
    code: 'WDG',
    name: 'Water Dispersible Granule',
    description: 'Granulated powder that disintegrates and disperses in spray tank.',
    best_for: ['Solid AIs needing dust-free handling', 'High loading solids'],
    advantages: ['Lower packaging volume than WP', 'Reduced dust vs WP'],
    limitations: ['Granulation capex', 'Caking in humid storage'],
    typical_ais: ['Mancozeb', 'Imidacloprid', 'Glyphosate salts'],
    processing_notes: ['Spray drying or extrusion', 'Binder + disintegrant selection critical'],
    tags: ['granule', 'solid'],
  },
  {
    code: 'WP',
    name: 'Wettable Powder',
    description: 'Powder blend that wets and suspends when added to water.',
    best_for: ['Solid AIs stable in dry form', 'Cost-sensitive markets'],
    advantages: ['No solvent', 'Long dry shelf life'],
    limitations: ['Dust exposure', 'Lower convenience vs liquids'],
    typical_ais: ['Mancozeb', 'Copper oxychloride'],
    processing_notes: ['Micronize before blending', 'Wetting agent essential'],
    tags: ['powder'],
  },
  {
    code: 'EW',
    name: 'Emulsion in Water (Oil in Water)',
    description: 'Oil phase dispersed as fine droplets in water with emulsifier system.',
    best_for: ['Liquid or dissolved hydrophobic AIs', 'Reduced solvent vs EC'],
    advantages: ['Lower VOC than EC', 'Good coverage'],
    limitations: ['Creaming', 'Ostwald ripening', 'Freeze-thaw'],
    typical_ais: ['Abamectin', 'Pyrethroids'],
    processing_notes: ['High shear emulsification', 'Antifreeze for cold climates'],
    tags: ['emulsion', 'aqueous'],
  },
  {
    code: 'SL',
    name: 'Soluble Concentrate',
    description: 'AI dissolves fully in aqueous or polar solvent system.',
    best_for: ['High water solubility actives or salts'],
    advantages: ['No particle suspension issues', 'Easy tank mixing'],
    limitations: ['Limited to soluble AIs', 'Hydrolysis in alkaline water'],
    typical_ais: ['Glyphosate', '2,4-D amine', 'Paraquat'],
    processing_notes: ['pH control', 'Compatibility with tank-mix partners'],
    tags: ['solution'],
  },
  {
    code: 'CS',
    name: 'Capsule Suspension',
    description: 'AI encapsulated in polymer shell dispersed in water.',
    best_for: ['Volatility control', 'Reduced skin contact', 'Controlled release'],
    advantages: ['Reduced odor and exposure', 'Improved rainfastness in some cases'],
    limitations: ['Complex manufacturing', 'Particle size control'],
    typical_ais: ['Lambda-cyhalothrin', 'Pendimethalin'],
    processing_notes: ['Interfacial polymerization', 'Strict QC on burst release'],
    tags: ['encapsulation'],
  },
  {
    code: 'SE',
    name: 'Suspo-Emulsion',
    description: 'Combination of suspended solid phase and emulsified liquid phase.',
    best_for: ['Tank-mix in bottle', 'Combo products solid + liquid AI'],
    advantages: ['Dual AI delivery', 'Single-pack convenience'],
    limitations: ['Phase stability complex', 'Regulatory combo constraints'],
    typical_ais: ['Mixed combo products'],
    processing_notes: ['Stabilize each phase separately before combination'],
    tags: ['combo'],
  },
];
