import type { KnowledgeIngredient } from '../types';

/** Curated agrochemical active ingredient database (handbook / FAO / pubchem summaries) */
export const KNOWLEDGE_INGREDIENTS: KnowledgeIngredient[] = [
  {
    id: 'chlorpyrifos',
    name: 'Chlorpyrifos',
    aliases: ['Lorsban', 'Dursban', 'CPF'],
    iupac_name: 'O,O-Diethyl O-(3,5,6-trichloropyridin-2-yl) phosphorothioate',
    cas_number: '2921-88-2',
    molecular_weight: 350.59,
    melting_point: 42,
    solubility_water: 1.4,
    log_p: 4.7,
    vapor_pressure: 2.5,
    pka: 0,
    technical_purity: 96.5,
    physical_form: 'solid',
    particle_size_d50: 8,
    hazard_class: 'Acute Tox. 3, Aquatic Acute 1',
    target_pest_category: 'insecticide',
    notes: 'Organophosphate insecticide. EC and SC common. Avoid alkaline hydrolysis.',
    references: ['FAO Specification 352', 'PubChem CID 2730'],
    tags: ['organophosphate', 'ec', 'sc'],
  },
  {
    id: 'glyphosate',
    name: 'Glyphosate',
    aliases: ['Roundup', 'GLY'],
    iupac_name: 'N-(phosphonomethyl)glycine',
    cas_number: '1071-83-6',
    molecular_weight: 169.07,
    melting_point: 189,
    solubility_water: 12000,
    log_p: -3.2,
    vapor_pressure: 0.01,
    pka: 2.3,
    technical_purity: 95,
    physical_form: 'solid',
    particle_size_d50: 15,
    hazard_class: 'Eye Irrit. 2',
    target_pest_category: 'herbicide',
    notes: 'SL and SG dominant. Requires surfactant for activity. Salt forms common.',
    references: ['FAO Glyphosate monograph', 'IUPAC pesticide manual'],
    tags: ['herbicide', 'sl', 'sg'],
  },
  {
    id: 'imidacloprid',
    name: 'Imidacloprid',
    aliases: ['Confidor', 'Admire'],
    iupac_name: '1-(6-chloropyridin-3-ylmethyl)-N-nitroimidazolidin-2-ylideneamine',
    cas_number: '138261-41-3',
    molecular_weight: 255.66,
    melting_point: 136,
    solubility_water: 610,
    log_p: 0.57,
    vapor_pressure: 0.02,
    pka: 11.1,
    technical_purity: 98,
    physical_form: 'solid',
    particle_size_d50: 5,
    hazard_class: 'Aquatic Chronic 1',
    target_pest_category: 'insecticide',
    notes: 'Neonicotinoid. SC, SL, WDG used. Sensitive to UV in some carriers.',
    references: ['PubChem CID 86287518'],
    tags: ['neonicotinoid', 'sc', 'wdg'],
  },
  {
    id: 'lambda-cyhalothrin',
    name: 'Lambda-cyhalothrin',
    aliases: ['Karate', 'Demand'],
    iupac_name: 'Cyano(3-phenoxyphenyl)methyl (1S,3S)-3-(2-chloro-3,3,3-trifluoroprop-1-enyl)-2,2-dimethylcyclopropanecarboxylate',
    cas_number: '91465-08-6',
    molecular_weight: 449.85,
    melting_point: 49,
    solubility_water: 0.005,
    log_p: 7,
    vapor_pressure: 0.2,
    pka: 0,
    technical_purity: 97,
    physical_form: 'solid',
    particle_size_d50: 3,
    hazard_class: 'Aquatic Acute 1, Skin Sens. 1',
    target_pest_category: 'insecticide',
    notes: 'Pyrethroid. EC and CS preferred. Low water solubility — emulsification critical.',
    references: ['FAO 463', 'CIPAC lambda-cyhalothrin'],
    tags: ['pyrethroid', 'ec', 'cs'],
  },
  {
    id: 'mancozeb',
    name: 'Mancozeb',
    aliases: ['Dithane', 'Manzate'],
    iupac_name: 'Manganese ethylenebis(dithiocarbamate) (polymeric) complex with zinc salt',
    cas_number: '8018-01-7',
    molecular_weight: 541,
    melting_point: 150,
    solubility_water: 6.2,
    log_p: 0.6,
    vapor_pressure: 0.01,
    pka: 0,
    technical_purity: 84,
    physical_form: 'solid',
    particle_size_d50: 6,
    hazard_class: 'Skin Sens. 1, Repr. 2',
    target_pest_category: 'fungicide',
    notes: 'Dithiocarbamate. WP and WG common. Decomposes in acidic conditions.',
    references: ['FAO 577'],
    tags: ['fungicide', 'wp', 'wdg'],
  },
  {
    id: 'abamectin',
    name: 'Abamectin',
    aliases: ['Vertimec', 'Avid'],
    iupac_name: 'Mixture of avermectin B1a and B1b',
    cas_number: '71751-41-2',
    molecular_weight: 873,
    melting_point: 150,
    solubility_water: 0.01,
    log_p: 4.4,
    vapor_pressure: 0.001,
    pka: 0,
    technical_purity: 95,
    physical_form: 'solid',
    particle_size_d50: 4,
    hazard_class: 'Acute Tox. 4',
    target_pest_category: 'insecticide',
    notes: 'EC and EW used. Light and oxygen sensitive. High molecular weight macrolide.',
    references: ['PubChem avermectin'],
    tags: ['macrolide', 'ec', 'ew'],
  },
  {
    id: '2-4-d',
    name: '2,4-D',
    aliases: ['2,4-Dichlorophenoxyacetic acid'],
    iupac_name: '(2,4-dichlorophenoxy)acetic acid',
    cas_number: '94-75-7',
    molecular_weight: 221.04,
    melting_point: 141,
    solubility_water: 31100,
    log_p: 2.81,
    vapor_pressure: 0.4,
    pka: 2.73,
    technical_purity: 98,
    physical_form: 'solid',
    particle_size_d50: 10,
    hazard_class: 'Acute Tox. 4',
    target_pest_category: 'herbicide',
    notes: 'SL and ester EC forms. Amine salts increase water solubility.',
    references: ['FAO 1'],
    tags: ['phenoxy', 'sl', 'ec'],
  },
  {
    id: 'atrazine',
    name: 'Atrazine',
    aliases: ['Aatrex'],
    iupac_name: '6-chloro-N2-ethyl-N4-isopropyl-1,3,5-triazine-2,4-diamine',
    cas_number: '1912-24-9',
    molecular_weight: 215.68,
    melting_point: 173,
    solubility_water: 33,
    log_p: 2.61,
    vapor_pressure: 0.4,
    pka: 1.85,
    technical_purity: 97,
    physical_form: 'solid',
    particle_size_d50: 12,
    hazard_class: 'Aquatic Chronic 2',
    target_pest_category: 'herbicide',
    notes: 'SC and WG. Triazine herbicide. Crystallization risk in cold storage.',
    references: ['EPA atrazine RRED'],
    tags: ['triazine', 'sc', 'wdg'],
  },
  {
    id: 'tebuconazole',
    name: 'Tebuconazole',
    aliases: ['Folicur', 'Raxil'],
    iupac_name: '1-(4-chlorophenyl)-4,4-dimethyl-3-(1H-1,2,4-triazol-1-ylmethyl)pentan-3-ol',
    cas_number: '107534-96-3',
    molecular_weight: 307.82,
    melting_point: 105,
    solubility_water: 36,
    log_p: 3.7,
    vapor_pressure: 0.2,
    pka: 13,
    technical_purity: 96,
    physical_form: 'solid',
    particle_size_d50: 4,
    hazard_class: 'Repr. 2',
    target_pest_category: 'fungicide',
    notes: 'Triazole fungicide. EC and SC. Stereochemistry affects activity.',
    references: ['FAO 620'],
    tags: ['triazole', 'ec', 'sc'],
  },
  {
    id: 'copper-oxychloride',
    name: 'Copper oxychloride',
    aliases: ['COC', 'Blitox'],
    iupac_name: 'Dicopper chloride trihydroxide',
    cas_number: '1332-40-7',
    molecular_weight: 427.14,
    melting_point: 250,
    solubility_water: 0.1,
    log_p: 0,
    vapor_pressure: 0,
    pka: 0,
    technical_purity: 85,
    physical_form: 'solid',
    particle_size_d50: 7,
    hazard_class: 'Aquatic Acute 1',
    target_pest_category: 'fungicide',
    notes: 'WP and WG. Inorganic fungicide. Abrasive — mill wear consideration.',
    references: ['CIPAC copper fungicides'],
    tags: ['inorganic', 'wp', 'wdg'],
  },
  {
    id: 'paraquat',
    name: 'Paraquat dichloride',
    aliases: ['Gramoxone'],
    iupac_name: '1,1\'-Dimethyl-4,4\'-bipyridinium dichloride',
    cas_number: '1910-42-5',
    molecular_weight: 257.16,
    melting_point: 300,
    solubility_water: 620000,
    log_p: -4.5,
    vapor_pressure: 0.01,
    pka: 0,
    technical_purity: 98,
    physical_form: 'solid',
    particle_size_d50: 20,
    hazard_class: 'Acute Tox. 1',
    target_pest_category: 'herbicide',
    notes: 'SL only. Highly regulated. Requires dye and emetic in many countries.',
    references: ['FAO 148'],
    tags: ['bipyridinium', 'sl'],
  },
  {
    id: 'azoxystrobin',
    name: 'Azoxystrobin',
    aliases: ['Amistar'],
    iupac_name: 'Methyl (E)-2-{2-[6-(2-cyanophenoxy)pyrimidin-4-yloxy]phenyl}-3-methoxyacrylate',
    cas_number: '131860-33-8',
    molecular_weight: 403.39,
    melting_point: 120,
    solubility_water: 6,
    log_p: 2.5,
    vapor_pressure: 0.01,
    pka: 0,
    technical_purity: 98,
    physical_form: 'solid',
    particle_size_d50: 3,
    hazard_class: 'Aquatic Acute 1',
    target_pest_category: 'fungicide',
    notes: 'Strobilurin. SC and WG. Photosensitive — use opaque packaging.',
    references: ['FAO 707'],
    tags: ['strobilurin', 'sc', 'wdg'],
  },
  {
    id: 'diquat',
    name: 'Diquat dibromide',
    aliases: ['Reglone'],
    iupac_name: '1,1\'-Ethylene-2,2\'-bipyridylium dibromide',
    cas_number: '85-00-7',
    molecular_weight: 344.05,
    melting_point: 335,
    solubility_water: 700000,
    log_p: -4.6,
    vapor_pressure: 0.01,
    pka: 0,
    technical_purity: 98,
    physical_form: 'solid',
    particle_size_d50: 18,
    hazard_class: 'Acute Tox. 2',
    target_pest_category: 'herbicide',
    notes: 'SL formulation. Contact desiccant. Synergist surfactants often required.',
    references: ['FAO 46'],
    tags: ['bipyridinium', 'sl'],
  },
  {
    id: 'pendimethalin',
    name: 'Pendimethalin',
    aliases: ['Prowl', 'Stomp'],
    iupac_name: 'N-(1-ethylpropyl)-3,4-dimethyl-2,6-dinitrobenzenamine',
    cas_number: '40487-42-1',
    molecular_weight: 281.31,
    melting_point: 54,
    solubility_water: 0.3,
    log_p: 5.4,
    vapor_pressure: 4,
    pka: 0,
    technical_purity: 96,
    physical_form: 'solid',
    particle_size_d50: 6,
    hazard_class: 'Aquatic Chronic 1',
    target_pest_category: 'herbicide',
    notes: 'EC and CS. Dinitroaniline. Soil incorporation important.',
    references: ['FAO 357'],
    tags: ['dinitroaniline', 'ec', 'cs'],
  },
  {
    id: 'metribuzin',
    name: 'Metribuzin',
    aliases: ['Sencor'],
    iupac_name: '4-amino-6-tert-butyl-3-(methylthio)-1,2,4-triazin-5(4H)-one',
    cas_number: '21087-64-9',
    molecular_weight: 214.28,
    melting_point: 126,
    solubility_water: 1050,
    log_p: 1.7,
    vapor_pressure: 0.5,
    pka: 0.5,
    technical_purity: 97,
    physical_form: 'solid',
    particle_size_d50: 8,
    hazard_class: 'Aquatic Chronic 2',
    target_pest_category: 'herbicide',
    notes: 'SC and WG. Triazinone. pH sensitive hydrolysis.',
    references: ['FAO 333'],
    tags: ['triazinone', 'sc', 'wdg'],
  },
  {
    id: 'spinetoram',
    name: 'Spinetoram',
    aliases: ['Delegate', 'Radiant'],
    iupac_name: 'Mixture of spinetoram-J and spinetoram-L',
    cas_number: '935545-74-1',
    molecular_weight: 756,
    melting_point: 140,
    solubility_water: 0.1,
    log_p: 4.5,
    vapor_pressure: 0.001,
    pka: 0,
    technical_purity: 92,
    physical_form: 'solid',
    particle_size_d50: 4,
    hazard_class: 'Aquatic Acute 1',
    target_pest_category: 'insecticide',
    notes: 'Spinosyn class. SC and WG. Fermentation-derived complex mixture.',
    references: ['EPA spinosad/spinetoram'],
    tags: ['spinosyn', 'sc'],
  },
  {
    id: 'propiconazole',
    name: 'Propiconazole',
    aliases: ['Tilt', 'Banner'],
    iupac_name: '1-[[2-(2,4-dichlorophenyl)-4-propyl-1,3-dioxolan-2-yl]methyl]-1H-1,2,4-triazole',
    cas_number: '60207-90-1',
    molecular_weight: 342.15,
    melting_point: 25,
    solubility_water: 100,
    log_p: 3.72,
    vapor_pressure: 0.4,
    pka: 0,
    technical_purity: 95,
    physical_form: 'liquid',
    particle_size_d50: 0,
    hazard_class: 'Repr. 2',
    target_pest_category: 'fungicide',
    notes: 'EC common — liquid AI. Triazole fungicide.',
    references: ['FAO 408'],
    tags: ['triazole', 'ec'],
  },
];
