import type { KnowledgeSurfactant } from '../types';

export const KNOWLEDGE_SURFACTANTS: KnowledgeSurfactant[] = [
  { id: 'morwet-d425', trade_name: 'Morwet D-425', chemical_class: 'Naphthalene sulfonate condensate', function: 'Dispersant', hlb_range: '12-14', typical_level: '2-6% w/w', formulation_types: ['SC', 'WDG', 'WP'], notes: 'Workhorse dispersant for SC milling.', tags: ['dispersant', 'sc'] },
  { id: 'atlox-4913', trade_name: 'Atlox 4913', chemical_class: 'Block copolymer', function: 'Dispersant / stabilizer', typical_level: '1-4% w/w', formulation_types: ['SC', 'EW'], notes: 'Steric stabilization in SC.', tags: ['dispersant'] },
  { id: 'rhodacal-ds4', trade_name: 'Rhodacal DS-4', chemical_class: 'Sodium dodecylbenzenesulfonate', function: 'Wetting agent', hlb_range: '10-12', typical_level: '0.5-2% w/w', formulation_types: ['SC', 'WP', 'WDG'], notes: 'Fast wetting for powders.', tags: ['wetting'] },
  { id: 'tween-20', trade_name: 'Tween 20', chemical_class: 'Polysorbate 20', function: 'Emulsifier / wetter', hlb_range: '16.7', typical_level: '0.5-3% w/w', formulation_types: ['EW', 'EC'], notes: 'Hydrophilic emulsifier for O/W.', tags: ['emulsifier', 'ew'] },
  { id: 'span-80', trade_name: 'Span 80', chemical_class: 'Sorbitan monooleate', function: 'Emulsifier', hlb_range: '4.3', typical_level: '1-5% w/w', formulation_types: ['EC', 'EW'], notes: 'Lipophilic emulsifier — pair with hydrophilic for HLB balance.', tags: ['emulsifier', 'ec'] },
  { id: 'calcium-dobs', trade_name: 'Calcium DDBS', chemical_class: 'Calcium dodecylbenzenesulfonate', function: 'Emulsifier (W/O)', typical_level: '2-8% w/w', formulation_types: ['EC'], notes: 'Classic EC emulsifier with nonionic co-emulsifier.', tags: ['ec'] },
  { id: 'xanthan-gum', trade_name: 'Xanthan Gum', chemical_class: 'Polysaccharide', function: 'Thickener / suspending aid', typical_level: '0.1-0.3% w/w', formulation_types: ['SC'], notes: 'Rheology modifier — pseudoplastic flow.', tags: ['thickener', 'sc'] },
  { id: 'attapulgite', trade_name: 'Attapulgite clay', chemical_class: 'Magnesium aluminum silicate', function: 'Thickener / anti-settling', typical_level: '0.5-2% w/w', formulation_types: ['SC'], notes: 'Inorganic thickener for high electrolyte systems.', tags: ['thickener'] },
  { id: 'antifoam-silicone', trade_name: 'Silicone antifoam', chemical_class: 'Polydimethylsiloxane emulsion', function: 'Antifoam', typical_level: '0.05-0.2% w/w', formulation_types: ['SC', 'EC', 'EW'], notes: 'Add late in process to avoid over-stabilizing foam.', tags: ['antifoam'] },
  { id: 'propylene-glycol', trade_name: 'Propylene glycol', chemical_class: 'Diol solvent', function: 'Antifreeze / co-solvent', typical_level: '5-15% w/w', formulation_types: ['EW', 'SL'], notes: 'Freeze-thaw stability in EW.', tags: ['solvent'] },
  { id: 'n-methyl-2-pyrrolidone', trade_name: 'NMP', chemical_class: 'Polar aprotic solvent', function: 'Solvent / penetrant', typical_level: '5-20% w/w', formulation_types: ['SL', 'EC'], notes: 'High solvency — check regulatory status in target markets.', tags: ['solvent'] },
  { id: 'citric-acid', trade_name: 'Citric acid', chemical_class: 'Organic acid', function: 'pH buffer', typical_level: '0.1-1% w/w', formulation_types: ['SC', 'SL'], notes: 'Buffer to pH 4-6 for alkaline-sensitive AIs.', tags: ['buffer'] },
  { id: 'bentonite', trade_name: 'Bentonite clay', chemical_class: 'Smectite clay', function: 'Thickener / stabilizer', typical_level: '1-3% w/w', formulation_types: ['SC'], notes: 'Gel network formation — pre-hydrate properly.', tags: ['thickener'] },
  { id: 'soprophor-4d384', trade_name: 'Soprophor 4D384', chemical_class: 'Tristyrylphenol ethoxylate phosphate', function: 'Emulsifier', typical_level: '3-8% w/w', formulation_types: ['EC'], notes: 'Anionic emulsifier for aromatic solvents.', tags: ['ec'] },
  { id: 'reax-85a', trade_name: 'Reax 85A', chemical_class: 'Lignosulfonate', function: 'Dispersant / binder', typical_level: '2-5% w/w', formulation_types: ['WDG', 'WP'], notes: 'Binder in WDG granulation.', tags: ['wdg', 'dispersant'] },
];
